// <auto-generated />
using System;
using MeetingAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetingAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MeetingAgentDbContext))]
    partial class MeetingAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.AgendaPlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalState")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("time");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "Version")
                        .IsUnique();

                    b.HasIndex("MeetingId", "ApprovalState", "Version");

                    b.ToTable("AgendaPlans", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.AgendaSectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AgendaPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacilitationNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<TimeSpan>("SuggestedDuration")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaPlanId", "Order")
                        .IsUnique();

                    b.ToTable("AgendaSections", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.FacilitatorAlertRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceSnippet")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId", "Timestamp");

                    b.ToTable("FacilitatorAlerts", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.MeetingRecapRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PacingSummary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TranscriptAvailability")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("MeetingId");

                    b.ToTable("MeetingRecaps", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.MeetingSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalendarEventId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("OrganizerIdentity")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset>("ScheduledEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamsChatId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TeamsMeetingId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerIdentity");

                    b.HasIndex("ScheduledEnd");

                    b.HasIndex("TeamsMeetingId");

                    b.ToTable("MeetingSessions", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.RecapActionItemRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("MeetingRecapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Owner")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRecapId");

                    b.ToTable("RecapActionItems", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.RecapInsightRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvidenceSnippet")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid>("MeetingRecapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingRecapId", "Kind");

                    b.ToTable("RecapInsights", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.TranscriptArtifactRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobContainerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MeetingId", "CreatedAt");

                    b.ToTable("TranscriptArtifacts", (string)null);
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.AgendaPlanRecord", b =>
                {
                    b.HasOne("MeetingAgent.Infrastructure.Persistence.Records.MeetingSessionRecord", "Meeting")
                        .WithMany("AgendaPlans")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.AgendaSectionRecord", b =>
                {
                    b.HasOne("MeetingAgent.Infrastructure.Persistence.Records.AgendaPlanRecord", "AgendaPlan")
                        .WithMany("AgendaSections")
                        .HasForeignKey("AgendaPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaPlan");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.FacilitatorAlertRecord", b =>
                {
                    b.HasOne("MeetingAgent.Infrastructure.Persistence.Records.MeetingSessionRecord", "Meeting")
                        .WithMany("FacilitatorAlerts")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.MeetingRecapRecord", b =>
                {
                    b.HasOne("MeetingAgent.Infrastructure.Persistence.Records.MeetingSessionRecord", "Meeting")
                        .WithMany("MeetingRecaps")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.RecapActionItemRecord", b =>
                {
                    b.HasOne("MeetingAgent.Infrastructure.Persistence.Records.MeetingRecapRecord", "MeetingRecap")
                        .WithMany("ActionItems")
                        .HasForeignKey("MeetingRecapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingRecap");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.RecapInsightRecord", b =>
                {
                    b.HasOne("MeetingAgent.Infrastructure.Persistence.Records.MeetingRecapRecord", "MeetingRecap")
                        .WithMany("Insights")
                        .HasForeignKey("MeetingRecapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingRecap");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.TranscriptArtifactRecord", b =>
                {
                    b.HasOne("MeetingAgent.Infrastructure.Persistence.Records.MeetingSessionRecord", "Meeting")
                        .WithMany("TranscriptArtifacts")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.AgendaPlanRecord", b =>
                {
                    b.Navigation("AgendaSections");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.MeetingRecapRecord", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Insights");
                });

            modelBuilder.Entity("MeetingAgent.Infrastructure.Persistence.Records.MeetingSessionRecord", b =>
                {
                    b.Navigation("AgendaPlans");

                    b.Navigation("FacilitatorAlerts");

                    b.Navigation("MeetingRecaps");

                    b.Navigation("TranscriptArtifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
